swagger: "2.0"
info:
  title: "ofertas de crédito"
  description: "API para retornar as ofertas de crédito para uma pessoa"
  version: 1.0.0
host: "localhost:8000"
basePath: /api/
schemes:
  - http
paths:
  /offers:
    get:
      summary: Retorna um JSON com as 3 melhores ofertas de credito
      parameters:
        - in: body
          name: Consulta de credito
          description: Dado um CPF e um valor desejado de credito é feita a busca de ofertas de credito para o CPF e valor informado
          schema:
            type: object
            required:
              - cpf
              - valorSolicitado
            properties:
              cpf:
                type: string
                example: 11111111111
              valorSolicitado:
                type: number
                example: 5000.00
      responses:
        "200":
          description: Requisição processada e retornado as ofertas
          schema:
            $ref: "#/definitions/responseOkWithData"
        "204":
          description: A requisição foi processada, mas nenhuma oferta foi encontrada
          schema:
            $ref: "#/definitions/responseOkWithoutData"
        "400":
          description: Verificar se todas as variaves de entrada foram informadas
          schema:
            $ref: "#/definitions/responseBad"
definitions:
  responseOkWithData:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 200
      offers:
        type: array
        items:
          $ref: "#/definitions/offerModel"
  responseOkWithoutData:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 204
      message:
        type: string
        example: Nenhuma oferta encontrada.
  responseBad:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 400
      message:
        type: string
        example: Verifique as informações
  offerModel:
    type: object
    properties:
      instituicaoFinanceira:
        type: string
        example: Banco ATR SA
      modalidadeCredito:
        type: string
        example: crédito pessoal
      valorAPagar:
        type: number
        example: 7959.0993958086
      taxaJuros:
        type: number
        example: 0.0395
      qntParcelas:
        type: integer
        example: 12
